# Generated by Django 3.2.13 on 2022-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_studentattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
