# Generated by Django 3.2.13 on 2022-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_auto_20220602_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='token',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
