# Generated by Django 3.2.13 on 2022-06-02 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0004_auto_20220602_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable')),
            ],
        ),
    ]
