# Generated by Django 3.2.13 on 2022-06-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('ALPHA', 'alpha'), ('HADIR', 'hadir'), ('IJIN', 'ijin')], default='ALPHA', max_length=20, null=True),
        ),
    ]
