# Generated by Django 3.2.13 on 2022-06-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_auto_20220602_0727'),
        ('attendances', '0002_auto_20220602_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable'),
        ),
    ]
