# Generated by Django 3.2.13 on 2022-06-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_timetable_token'),
        ('attendances', '0003_alter_studentattendance_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='name',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('ALPHA', 'alpha'), ('HADIR', 'hadir'), ('IJIN', 'ijin')], default='ALPHA', editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='timetable',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable'),
        ),
    ]
