# Generated by Django 3.2.13 on 2022-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_auto_20220602_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='token',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
