# Generated by Django 3.2.13 on 2022-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ManyToManyField(to='classrooms.Classroom'),
        ),
    ]
