# Generated by Django 3.2.13 on 2022-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_subject_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classroom',
            field=models.ManyToManyField(related_name='subjects', to='classrooms.Classroom'),
        ),
    ]
