# Generated by Django 3.2.13 on 2022-06-01 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0003_alter_subject_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(related_name='kelasku', to=settings.AUTH_USER_MODEL),
        ),
    ]
