# Generated by Django 3.2.13 on 2022-06-20 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=40)),
                ('homeroom_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wali_kelas', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(related_name='kelasku', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=15)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classrooms.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=4, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroomsubject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ALPHA', 'alpha'), ('HADIR', 'hadir'), ('IJIN', 'ijin')], default='ALPHA', max_length=20, null=True)),
                ('token', models.CharField(blank=True, max_length=4)),
                ('timetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroomtimetable')),
            ],
        ),
    ]
