# Generated by Django 3.2.13 on 2022-06-20 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='classroomattendance',
            options={'verbose_name_plural': 'Kehadiran Kelas'},
        ),
        migrations.AlterModelOptions(
            name='classroomsubject',
            options={'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='classroomtimetable',
            options={'verbose_name_plural': 'Jadwal Kelas'},
        ),
        migrations.RemoveField(
            model_name='classroomattendance',
            name='name',
        ),
        migrations.AddField(
            model_name='classroomattendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
