# Generated by Django 3.2.13 on 2022-06-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20220620_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomattendance',
            name='token',
        ),
    ]
