# Generated by Django 3.2.13 on 2022-06-20 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_time', models.TimeField()),
                ('home_time', models.TimeField()),
                ('role', models.CharField(choices=[('MRD', 'Student'), ('KWN', 'Staff'), ('GRU', 'Teacher'), ('MRD_HOME', 'Student Home'), ('KWN_HOME', 'Staff Home'), ('GRU_HOME', 'Teacher Home')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.TimeField()),
                ('clock_out', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.attendancetimetable')),
            ],
        ),
    ]
