# Generated by Django 3.2.13 on 2022-07-13 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_time', models.TimeField()),
                ('home_time', models.TimeField()),
                ('role', models.CharField(choices=[('MRD', 'Student'), ('KWN', 'Staff'), ('GRU', 'Teacher'), ('MRD_HOME', 'Student Home'), ('KWN_HOME', 'Staff Home'), ('GRU_HOME', 'Teacher Home')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Penjadwalan Umum',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[('HALF', '1'), ('FULL', '2')], default=1)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('attachment', models.ImageField(upload_to='')),
                ('approve', models.BooleanField(default=None, null=True)),
                ('lecture', models.ManyToManyField(to='classrooms.ClassroomSubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.attendancetimetable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Hadir',
            },
        ),
    ]
