# Generated by Django 3.2.13 on 2022-06-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Daftar Hadir'},
        ),
        migrations.AlterModelOptions(
            name='attendancetimetable',
            options={'verbose_name_plural': 'Penjadwalan Umum'},
        ),
    ]
