# Generated by Django 3.2.13 on 2022-07-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0003_remove_classroomattendance_token'),
        ('attendances', '0002_auto_20220624_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[('HALF', '1'), ('FULL', '2')], default=1)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('attachment', models.ImageField(upload_to='')),
                ('approve', models.BooleanField(default=None, null=True)),
                ('lecture', models.ManyToManyField(to='classrooms.ClassroomSubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
