# Generated by Django 3.2.13 on 2022-07-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_auto_20220720_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_mode',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Full'), (1, 'Half')]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Ijin'), (1, 'Sakit')]),
        ),
    ]
